//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_ID { get; set; }
        public string Food_weeklist { get; set; }
        public string ExerciseList { get; set; }
        public string DrugList { get; set; }
        public int User_ID { get; set; }
        public int Matching_Matching { get; set; }
        public int User_User_ID { get; set; }
    
        public virtual Matching Matching { get; set; }
    }
}
