//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Group
    {
        public int User_Group_ID { get; set; }
        public int User_User_ID { get; set; }
        public int Group_group_ID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
