//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matching
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matching()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int Matching_ID { get; set; }
        public int Food_Food_ID { get; set; }
        public int Exercise_Ex_ID { get; set; }
        public int Drug_Drug_ID { get; set; }
        public int User_User_ID { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Exercise Exercise { get; set; }
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
